{% set version = "1.15.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-treetools
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/TreeTools_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/TreeTools/TreeTools_{{ version }}.tar.gz
  sha256: 3e5a311111e3679724ef6c7bcd33c1e0a3e898379a90fc81cb10da37185f4319

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  # Checking windows to see if it passes. Uncomment the line if it fails.
  # skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-ape >=5.6
    - r-bit64
    - r-colorspace
    - r-fastmatch >=1.1.3
    - r-lifecycle
    - r-plottools
    - r-r.cache
    - r-rcurl
    - r-rcpp
    - r-rdpack >=2.3
  run:
    - r-base
    - r-ape >=5.6
    - r-bit64
    - r-colorspace
    - r-fastmatch >=1.1.3
    - r-lifecycle
    - r-plottools
    - r-r.cache
    - r-rcurl
    - r-rcpp
    - r-rdpack >=2.3

test:
  commands:
    - $R -e "library('TreeTools')"           # [not win]
    - "\"%R%\" -e \"library('TreeTools')\""  # [win]

about:
  home: https://ms609.github.io/TreeTools/
  dev_url: https://github.com/ms609/TreeTools/
  license: GPL-3.0-or-later
  summary: 'Efficient implementations of functions for the creation, modification and analysis of phylogenetic trees. Applications include: generation of trees with specified shapes; rooting of trees and extraction of subtrees; calculation and depiction of node support; calculation of ancestor-descendant relationships; import
    and export of trees from Newick, Nexus (Maddison et al. 1997) <doi:10.1093/sysbio/46.4.590>, and TNT <http://www.lillo.org.ar/phylogeny/tnt/> formats; and analysis of splits and cladistic information.'
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
